### ISSUE TITLE
Editor roles are still getting assigned contractor values

### ISSUE THREAD

**Issue by chucklapointe** [narcitymedia/lilium-cms#339]
**Describe the bug**

It seems like Editors still randomly get articles assigned with a value to them in the Payment Dashboard. I'm not sure why this is happening.

**To Reproduce**

I'm not sure of the best way to reproduce this.

**Expected behavior**

Editors should not have contractor amounts assigned to their articles.

**Screenshots**

For now, our accounting team is assigning 0$ to those articles before processing, but it's not ideal, they shouldn't appear in the Payment Dashboard at all.

**Section**

Payment dashboard

**Comment by rykdesjardins** [comment]
I think this is my fault when I ran the script to assign missing values after deploying V4 live. 

@chucklapointe Do you know if the articles from editors assigned with a value are newer than April 15th? If not, We can simply set the status of those posts to "paid" since the recent posts don't have a value assigned if written by staff.

**Comment by chucklapointe** [comment]
Yes I can confirm.
I can close this then

Thanks for clarifying
