### ISSUE TITLE
Prevent authors from accidentally leaving article page with pending modifications

### ISSUE THREAD

**Issue by Gaboik** [narcitymedia/lilium-cms#342]
# The Problem
Since V4, the auto-save behavior was modified so that the article saves whenever the `<TextEditor />` loses focus. However, if the author, for instance, modifies the article and presses the 'back button' of his browser, the 'focus out' event won't be fired and the component will be unmounted without saving.

# Possible Solutions
1. Save article on `componentWillUnmount()`. This tho has its limits because if the user navigates away from Lilium, the request will likely not have enough time to execute.
2. Take advantage of the [window.beforeunload event](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) to confirm navigation when an author has pending modifications.
3. Re implement an auto-save behavior that would save the article at a regular interval

**Comment by rykdesjardins** [comment]
For now we'll go with options 3! It's a quick fix until we can figure out something better. At some point, I'd like all component mounted by the URL Renderer to have a method that can be called before switching page. 

That way, those components could validate that they can actually unmount, or simply make async calls before letting the URL Renderer render something else. There's not much we can do when it comes to closing the tab since the beforeunload event is purely sync. Doing network calls inside this callback might not work. 

We can also auto-save every time the websocket reconnects, and at other moments that are not time-sensitive.
