### ISSUE TITLE
Snippet widget inside TinyMCE

### ISSUE THREAD

**Issue by rykdesjardins** [narcitymedia/lilium-cms#352]
**Is your feature request related to a problem? Please describe.**
Some text is often repeated. 

**Describe the solution you'd like**
It would be a quick addition to create an "insert snippet" button in TinyMCE. Creating those would require a permission, but anyone could use them. 

**Are you currently using a workaround? If so, please describe it.**
Copy pasting from a third-party.

**Comment by Gaboik** [comment]
We stumbled upon a possible actual use case for this, for example, when the sponsored content writers want to insert the sponsored logo at the top of the content of an article, right now, they are copying and pasting it from an external document, this could be easily solved by the snippet feature and would also allow for easy modification, right now, each writer has their own copy of the markup, making it hard to modify effectively.

**Comment by Gaboik** [comment]
After discussion with @lauriebergeron we decided that the best way to insert the templates in the article content would be to insert the template's markup directly inside the article's content. However, the template's markup will be wrapped inside something like a `<div class='lilium-template {templateid}'>{templatemarkup}</div>` because I have a gut feeling that it could be useful in the future if we ever need to find all references to a template in the database.

Also, since the templates are going to use [TinyMCE's template plugin](https://www.tiny.cloud/docs/plugins/template/), from now on, we are going to call them **templates instead of snippets**.
